baseURL = "https://github.com/CognotektGmbH.github.io"
#baseURL = "http://cognotekt.wanjarunkel.de/"

# set the default language to german
defaultContentLanguage = "de"
title = "Cognotekt-multi.com"
theme = "hugo-universal-theme"
# Enable Google Analytics by entering your tracking code
#googleAnalytics = ""
publishDir = "public"

#
# add the menu to the page
#

# german menu
[languages.de]
weight = 0
languageName = "Deutsch"

[[languages.de.menu.main]]
url    = "/"
name   = "Startseite"
weight = 1

[[languages.de.menu.main]]
url    = "/"
name   = "Blog"
weight = 2

[[languages.de.menu.main]]
url    = "/en"
name   = "Englisch"
weight = 10

# englisch menu
[languages.en]
weight = 10
languageName = "English"

[[languages.en.menu.main]]
url    = "/"
name   = "Home"
weight = 1

[[languages.en.menu.main]]
url    = "/"
name   = "Blog"
weight = 2

[[languages.en.menu.main]]
url    = "/"
name   = "German"
weight = 10

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable and disable recent posts in the footer
[params.recent_posts]
    enable = true
    title = "In the News"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."